name: MultiCodeBench
dependencies:
  - python=3.8
  - pip=24.0
  - pip:
      - annotated-types==0.7.0
      - astor==0.8.1
      - black==24.8.0
      - blobfile==3.0.0
      - certifi==2024.2.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - editdistance==0.6.2
      - filelock==3.15.4
      - fonttools==4.51.0
      - fpdf==1.7.2
      - fsspec==2024.6.1
      - gensim==4.3.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.24.6
      - idna==3.7
      - importlib-resources==6.4.0
      - inflection==0.5.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lxml==5.3.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.0
      - pathspec==0.12.1
      - pillow==10.3.0
      - platformdirs==4.2.2
      - pycryptodomex==3.20.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.5.15
      - requests==2.32.2
      - scipy==1.10.1
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - stdlib-list==0.10.0
      - sympy==1.13.2
      - tiktoken==0.1.2
      - tokenizers==0.13.3
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==2.4.0
      - tqdm==4.66.4
      - transformers==4.24.0
      - tree-sitter==0.21.3
      - tree-sitter-solidity==0.0.2
      - tree-sitter-types==0.0.2
      - triton==3.0.0
      - typing-extensions==4.12.2
      - urllib3==2.2.1
      - wordcloud==1.9.3
      - wrapt==1.16.0
      - zipp==3.18.2
